<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace tutorial;

class tutorial_CONSTANTS {
  /**
   * Thrift also lets you define constants for use across languages. Complex
   * types and structs are specified using JSON notation.
   */
  const INT32CONSTANT = 9853;
  static $MAPCONSTANT = array(
      "hello" => "world",
      "goodnight" => "moon",
    );

  public static $__values = array(
    "INT32CONSTANT" => 9853,
    "MAPCONSTANT" => array(
        "hello" => "world",
        "goodnight" => "moon",
      ),
  );
}

$GLOBALS['tutorial_CONSTANTS'] = tutorial_CONSTANTS::$__values;

?>
